import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <nav className="flex justify-between items-center px-8 py-4 bg-white border-b border-gray-200 shadow-sm rounded-md">
          <a
            className="text-xl font-bold text-green-600 hover:text-green-700"
            href="/"
          >
            Performance Tracker
          </a>
          <div className="flex gap-6">
            <a
              className="text-gray-700 hover:text-green-700 font-medium"
              href="/employees"
            >
              Employees
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
